"""
Purpose of this script is to provide modules for quickly plotting the results of the "toy model" and the Artificial
Neural Network, as a part of this surrogate model experimentation.

Author: Allan E. Jones
Date: 28 May 2026
"""
from mpl_toolkits.mplot3d import Axes3D
import flopy
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mp
import os
# suppress matplotlib warning (3d plot is angry at nan values but still works)
import warnings
warnings.filterwarnings("ignore")

def headContourPlot(model, head, frf, fff,
                    title, subtitle, grid=True, cmap='viridis',
                    plot_disch=True, fs=(8, 8)):
    """
    This function generates the head contour plot (with groundwater discharge flowlines) for the model cells. Figure
    provides a plane view of the model with head pressure contours, model cell gridlines, and discharge arrows.

    **ISWS**: Modules were originally developed by Daniel's student Shelby. The syntax in these scripts could likely
    be updated to more modern syntax for instruction purposes. **GOOD LEARNING TASK OPPORTUNITY**

    Parameters
    ----------
    model - MODFLOW model instance
    head - numpy array of head values that are generated by the model - shape [sp, layers, rows, columns]
    frf - a CBC flow output from the MOWFLOW model, describes net Flow through the Right Face
    fff - a CBC flow output from the MOWFLOW model, describes net Flow through the Front Face
    title - string; title needed for the generated figure
    subtitle - string; subtitles for the generated figure
    grid - boolean; T or F statement about whether to include the gridlines on the plot
    cmap - string; desired colormap for the head contours. Default = 'viridis'.
    plot_disch - boolean; T or F statement about whether to also plot discharge arrows
    fs - tuple; defines the desired figure size.

    Returns
    -------
    fig - matplotlib figure generated by the function

    """
    # data, color-plotting setup
    masked = np.ma.masked_where(model.bas6.ibound.array == 0, head)  # mask inactive cells cells
    ticker = mp.ticker.MaxNLocator(nbins=model.dis.ncol)
    levels = ticker.tick_values(np.min(masked), np.max(masked))  # set contour levels
    cmap = plt.get_cmap(cmap)  # get colormap
    norm = mp.colors.BoundaryNorm(levels, ncolors=cmap.N, clip=True)  # normalize colormap to dataset levels

    # create figure and plots
    fig, ax = plt.subplots(figsize=fs)  # create figure
    modelmap = flopy.plot.PlotMapView(model=model, layer=0, ax=ax)  # use modelmap to attach plot to model
    pcolor = modelmap.plot_array(masked, norm=norm, animated=True)  # create contours
    if grid is True:
        grid = modelmap.plot_grid()  # plot grid if True
    if plot_disch is True:
        modelmap.plot_vector(frf[0], fff[0])  # create discharge arrows if true

    # figure display parameters
    plt.xlabel('Lx (m)', fontsize=13)
    plt.ylabel('Ly (m)', fontsize=13)
    plt.suptitle(title, fontsize=20, fontweight='bold', x=.44, y=.98)  # bold title
    plt.title(subtitle, fontsize=14, y=1.015)  # subtitle
    cb = plt.colorbar(pcolor)
    cb.set_label('Head (m)', fontsize=13, labelpad=12)  # add colorbar for head data
    plt.show()
    return fig


def headSurfacePlot(model, Lx, Ly, head,
                    title='', cmap='viridis', fs=(12, 5)):
    """
    This function generates a 3D surface plot of groundwater head pressures generated from a MODFLOW model.

    **ISWS**: Modules were originally developed by Daniel's student Shelby. The syntax in these scripts could likely
    be updated to more modern syntax for instruction purposes. **GOOD LEARNING TASK OPPORTUNITY**

    Parameters
    ----------
    model - instance of a MODFLOW model from which to generate the head surface plot
    Lx - int of float; the length of the model in the x-direction
    Ly - int of float; the length of the model in the y-direction
    head - numpy array of head values that are generated by the model - shape [sp, layers, rows, columns]
    title - string; title needed for the generated figure
    cmap - string; desired colormap for the head contours. Default = 'viridis'.
    fs - tuple; defines the desired figure size.

    Returns
    -------
    fig3d - 3D matplotlib figure generated by the function

    """
    # create 3d figure
    fig_3d = plt.figure(figsize=fs)
    ax = fig_3d.add_subplot(111, projection='3d')

    # set up data space
    #    masked = np.where(model.bas6.ibound.array !=0, head, np.nan)
    masked = head[:, 1:-1, :]
    x = np.linspace(0, Lx, model.dis.ncol)  # set x domain using model dis pkg
    y = np.linspace(0, Ly, model.dis.nrow)  # set y domain using model dis pkg
    #    x, y = np.meshgrid(x, y) #mesh domain
    x, y = np.meshgrid(x, y[1:-1])  # mesh domain

    # set color levels
    levels = np.linspace(np.nanmin(masked),
                         np.nanmax(masked),
                         model.dis.ncol - 1)
    cmap = plt.get_cmap(cmap)  # get colormap
    norm = mp.colors.BoundaryNorm(levels, ncolors=cmap.N, clip=True)  # normalize colormap to dataset values
    surf = ax.plot_surface(x, y, np.flipud(masked[0]),
                           cmap=cmap, linewidth=0, antialiased=False,
                           label='head', norm=norm)  # plot active head surface
    surf.set_facecolor((0, 0, 0, 0))
    cb = fig_3d.colorbar(surf, shrink=0.5, aspect=5)
    cb.set_label('Head (m)', fontsize=15, labelpad=10)  # add colorbar
    ax.set_xlabel('Lx (m)', fontsize=13, labelpad=10)
    ax.set_ylabel('Ly (m)', fontsize=13, labelpad=10)
    ax.set_title(title, fontsize=15, y=1.05)
    plt.show()
    return fig_3d

def xyzcellcenters_3d(mf):
    """
    Calculate 3D np.arrays of x-, y-, z- coodinate locations for each model cell node

    Parameters
    ----------
    mf - MODFLOW-NWT model object

    Returns
    -------
    xmesh - np.array of shape (layers, rows, columns), x-coordinate locations of model cell nodes

    ymesh - np.array of shape (layers, rows, columns), y-coordinate locations of model cell nodes

    zzz - np.array of shape (layers, rows, columns), z-elevations of model cell nodes
    """
    xxx, yyy, zzz = mf.modelgrid.xyzcellcenters
    xmesh = np.ones(zzz.shape)*-999
    ymesh = np.ones(zzz.shape)*-999
    for l in range(zzz.shape[0]):
        xmesh[l] = xxx
        ymesh[l] = yyy

    return xmesh, ymesh, zzz

def find_min_dist_and_value(mf, pkg_spd, key='stage'):
    """
    Calculates distance of each model cell to the nearest instance of a particular package cell (e.g., wel,
    riv) in the model. Also, returns the pertinent values (e.g., 'stage',  'flux') for that nearest package cell.

    Parameters
    ----------
    mf - MODFLOW-NWT model object

    pkg_spd - np.recarray, stress period data for a specified MODFLOW-NWT package (e.g., RIV, WEL, etc.)

    key - str, field/key for the np.recarray (`pkg_spd`) which denotes the pertinent simulated data to obtain from
    the model object.

    Returns
    -------
    dist - np.array of shape (layers, rows, columns), minimum distance from each cell to the nearest cell using the
    desired MF package (e.g., wel, riv)

    value - np.array of shape (layers, rows, columns), the pertinent (i.e., coordinated by key) value of the nearest
    package cell to each model cell

    """
    # package locations
    idx = (pkg_spd['k'], pkg_spd['i'], pkg_spd['j'])
    # model cell centers in 3d arrays
    xxx, yyy, zzz = xyzcellcenters_3d(mf)

    # find distance from package points
    stor1 = np.zeros((len(idx[0]), xxx.shape[0], xxx.shape[1], xxx.shape[2]))
    for n, i in enumerate(zip(idx[0], idx[1], idx[2])):
        stor1[n] = np.sqrt(((xxx - xxx[i]) ** 2) +
                           ((yyy - yyy[i]) ** 2) +
                           ((zzz - zzz[i]) ** 2))
    # calculate minimum distance and the values associated with package for each nearby cell
    dist = np.min(stor1, axis=0)
    min_idx = np.argmin(stor1, axis=0)
    value = pkg_spd[key][min_idx]
    return dist, value