name: isws-demonstration-models

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - ffmpeg
  - flopy
  - matplotlib=3.7.2
  - numpy
  - openpyxl
  - pandas
  - pip
  - pyyaml
  - shapely