name: isws-demonstration-models
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12 # tensorflow needs 3.9-3.12 (19 Sept 2025)
  - flopy
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pip
  - pyyaml
  - shapely
  - pip:
      -tensorflow # surrogate addition